api/urls.py
from django.urls import path
from .views import *

urlpatterns = [    
    path('v1/imgprincipal/<int:pk>', Image_APIView.as_view(), name='imgprincipal'),
    path('v1/imagenes/<int:pk>', Images_APIView.as_view(), name='imagenes'),
    path('v1/producto/<int:pk>', Producto_APIView.as_view(), name='producto'),
    path('v1/productosusuario/<int:pk>', ProductosUsuario_APIView.as_view(), name='productosusuario'),
    path('v1/productos', Productos_APIView.as_view(), name='productos'),
    path('v1/sucursales', Sucursal_APIView.as_view(), name='sucursales'),
    path('v1/categoriasprecio', CategoriaPrecio_APIView.as_view(), name='categoriasprecio'),
    path('v1/estado_producto', EstadoProducto_APIView.as_view(), name='estado_producto'),
    path('v1/estado_producto/<int:id>', EstadoProductoId_APIView.as_view(), name='estado_producto_id'),
    path('v1/promociones/', Promocion_APIView.as_view(), name='promociones'),
    path('v1/es_promocionado/<int:pk>', Promocion_Producto_APIView.as_view(), name='es_promocionado'),
    ]

fedeteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

def notFound(request):
    return render(request, '404.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('publico.urls', 'publico'), namespace='publico')),
    path('administracion/', include(('administracion.urls', 'administracion'), namespace='administracion')),
    path('moderacion/', include(('moderacion.urls', 'moderacion'), namespace='moderacion')),
    path('trueques/', include(('trueques.urls', 'trueques'), namespace='trueques')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('promociones/', include(('promociones.urls', 'promociones'), namespace='promociones')),
    path('404/', notFound),
]

publico/urls.py
from django.contrib import admin
from django.urls import path, include
from publico.views import *

urlpatterns = [
    # _-_-_-_ _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
    # _-_-_-_ urls sin login required _-_-_-_
    path('', inicio, name='inicio'),
    path('sucursales', sucursales, name='sucursales'),
    path('not-found', notFound, name='not-found'),
    path('emails/register', emailsRegister),

        # productos visualizacion y acciones
    path('productos', verProductos, name='productos'),
    path('productos/producto/<id>', verProducto),

    path('usuario/<username>', verUsuario, name='verUsuario'),   #dni basicamente

        # relacionado a auth
    path('register', registrarUsuario, name='registrarUsuario'),
    path('register/done', registrarSuccess, name='registrarSuccess'),
    path('login', userLogin, name='login'),
    path('logout', logout_view, name='logout'),

    # _-_-_-_ _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
    # _-_-_-_ urls con login required _-_-_-_
    path('perfil', verPerfil, name='perfil'),
    path('perfil/editar', editarPerfil, name='editarPerfil'),

    path('perfil/cambiarcontrasenia', cambiarContrasenia, name='cambiarContrasenia'),
    path('perfil/cambiarcontrasenia/done', cambiarContraseniaSuccess, name='cambiarContraseniaSuccess'),

    # a partir de aca accedido solo por clientes!
    path('perfil/cargarProducto', cargarProducto, name='cargarProducto'),
    path('perfil/cargarProducto/done', cargarProductoSuccess, name='cargarProductoSuccess'),

    path('perfil/productos', verProductosPerfil, name='verProductosPerfil'),
    path('perfil/productos/producto/<id>', verProductoPerfil),
    path('perfil/productos/producto/eliminar/<id>', eliminarProducto, name='eliminarProducto'),
    path('perfil/solicitudes', listarSolicitudesTrueque, name='solicitudesTrueques'),
    path('perfil/solicitudesAceptadas', listarSolicitudesTruequesAceptados, name='intercambiosEnProceso'),
    path('perfil/intercambiosTerminados', listarTruequesTerminados, name='intercambiosTerminados'),
    path('perfil/solicitudesCanceladas', listarSolicitudesCanceladas, name='intercambiosCancelados'),
    path('perfil/verTrueque/<id>', verTrueque, name='verTrueque'),
    path('perfil/calificarUsuario/<id>', calificarUsuario, name='calificarUsuario'),
    path('perfil/calificarUsuarioDone', calificarUsuarioSuccess, name='calificarUsuarioSuccess'),
    ]

trueques/urls.py
from django.urls import path
from trueques.views import *

urlpatterns = [    
    path('iniciar/<int:id>', seleccionarProductoTrueque, name='iniciar'),
    path('iniciar', iniciarTrueque, name='iniciarTrueque'),
    path('establecer-como-realizado', establecerEstadoRealizado, name='establecerEstadoRealizado'),
    path('establecer-como-no-realizado', establecerEstadoNoRealizado, name='establecerEstadoNoRealizado'),
    path('establecerSucursal/<id>', establecerSucursal, name='establecerSucursal'),
    path('establecerSucursalDone', establecerSucursalSuccess, name='establecerSucursalSuccess'),
    path('aceptartrueque/<int:id>', aceptarTrueque, name='aceptar_trueque'),
    path('cancelartrueque/<int:id>', cancelarTrueque, name='cancelar_trueque'),
]

publico/views.py
import datetime
from django.conf import settings

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib import messages
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.hashers import check_password
from rest_framework.decorators import api_view
from django.core.files.base import ContentFile
from django.db.models import Q
from fedeteria.utilities import actualizar_calificacion_usuario, iniciar_estados_productos, iniciar_sucursales, iniciar_tags, inicializar_categorias_precios, tiempo_pasado
from datetime import date

from promociones.models import Promocion
from publico.models import *
from trueques.models import Trueque

def inicio(request):
    iniciar_sucursales()
    iniciar_tags()
    inicializar_categorias_precios()
    iniciar_estados_productos()
    #productos = Producto.objects.all(filter(estado_publicacion="Activo")) #deberia hacer esto
    productos = Producto.objects.all()[:5] #me quedo con los primeros 5 productos
    _productos = [{'producto': producto,
                   'imagen': Image.objects.get(producto=producto,principal=True),
                   'tags': list(producto.tags.all()),
                   'tiempo_publicacion': tiempo_pasado(producto.fecha_publicacion),
                   } for producto in productos]
    #promociones activas de productos
    destacados = Promocion.objects.filter(Q(estado_pago='Pagado') & Q(fecha_inicio__lte=date.today()) & Q(fecha_fin__gte=date.today()))
    _destacados = [{'producto': Producto.objects.get(id=promocion.producto_id), 'imagen': Image.objects.get(producto_id=promocion.producto_id, principal=True)} for promocion in destacados]
    return render(request, 'publico/landingPage.html',{'productos':_productos, 'destacados':_destacados, 'selected': "inicio"})

def sucursales(request):
    sucursales = Sucursal.objects.all()
    return render(request, "publico/sucursales.html", {'sucursales': sucursales, 'selected': "sucursales"})

def notFound(request):
    return render(request, "publico/not-found.html")

def emailsRegister(request):
    return render(request, "emails/register.html", {'receiver_name': "Juan Manuel Vila"})


''' --------------- Login / Logout ------------------ '''

def logout_view(request):
    logout(request)
    return redirect('publico:inicio')

@api_view(["GET","POST"])
def userLogin(request):
    if request.user.is_authenticated:
        return redirect("/perfil")

    if request.method == 'POST':
        user = authenticate(request, username=request.POST["dni"], password=request.POST["password"])
        if user is not None:
            login(request, user)

            #acá un condicional para redirigir depende del privilegio que tenga el usuario
            if user.has_perm('publico.admin'):
                return redirect('administracion:inicio') #cambiar a pagina admin
            else:
                if user.has_perm('publico.empleado'):
                    return redirect('/moderacion') #cambiar a pagina empleado
                else:
                    return redirect('publico:perfil')
        else:
            messages.error(request, "Usuario o contraseña invalidos...")
            return redirect('publico:login') #redirect!
    else:
        return render(request, 'publico/login/login.html')

''' --------------- Usuarios ------------------ '''

@api_view(["GET","POST"])
def registrarUsuario(request):
    iniciar_sucursales()
    if request.user.is_authenticated:
        return redirect("/perfil")

    if request.method == 'POST':
        info = request.POST
        if info["repeat_password"] != info["password"]:
            messages.error(request, "Error: Las contraseñas no coinciden!", extra_tags="text-red-400")
            return redirect('publico:registrarUsuario')

        try:
            exists = User.objects.get(username=info["dni"], email=info["email"])
            if exists is not None:
                messages.error(request, "Error: Algunos datos ya estan registrados. Intentalo de nuevo o Inicia Sesion", extra_tags="text-yellow-400")
                return redirect('publico:registrarUsuario')
        except:
            #buscando la sucursal segun lo pasado desde el form
            sucursal = Sucursal.objects.get(id=info["sucursal"])

            new_user = User.objects.create_user(
                username= info["dni"],
                first_name = info["first-name"],
                last_name = info["last-name"],
                email = info["email"],
                password = info["password"],
            )
            new_user.save()
            user = User.objects.get(username = info["dni"])
            #Permiso de usuario cliente
            content_type = ContentType.objects.get_for_model(Permisos)
            permiso = Permission.objects.get(codename='cliente', content_type=content_type)
            # Asignar el permiso al usuario
            user.user_permissions.add(permiso)
            usuario = Usuario.objects.create(
                user = user,
                fecha_nacimiento = info["born"],
                avatar = info["avatar"],
                telefono = info["phone"],
                sucursal_id = sucursal.id,
                ofertas = info.get("offers") is not None,
            )
            usuario.save()

            subject = 'Bienvenido '+ user.first_name +'. Ahora a intercambiar!'
            convert_to_html_content =  render_to_string(
                template_name= 'emails/register.html',
                context= {
                    'user': user,
                    'usuario': usuario
                }
            )
            plain_message = strip_tags(convert_to_html_content)
            send_mail(
                subject=subject,
                message=plain_message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email],   # recipient_list is self explainatory
                html_message=convert_to_html_content,
            )

            return redirect("/register/done")
    else:
        return render(request, 'publico/login/registrarUsuario.html')

def registrarSuccess(request):
    if request.user.is_authenticated:
        return redirect("/perfil")
    return render(request, "publico/login/registrarSuccess.html")


@api_view(["GET","POST"])
@login_required(login_url='publico:login')
def editarPerfil(request):
    if request.method == 'POST':
        info = request.POST
        user = User.objects.get(username=request.user.username)
        usuario = Usuario.objects.get(user_id=user.id)
        user.first_name = info["first-name"]
        user.last_name = info["last-name"]
        user.email = info["email"]
        user.save()
        usuario.avatar = info["avatar"]
        usuario.telefono = info["phone"]
        usuario.fecha_nacimiento = info["born"]
        usuario.ofertas = info.get("offers") is not None
        usuario.sucursal = Sucursal.objects.get(id=info["sucursal"])
        usuario.save()
        return render(request, 'publico/usuario/editarPerfilSuccess.html')
    usuario = Usuario.objects.get(user_id=request.user.id)
    return render(request, 'publico/usuario/editarPerfil.html', {'sidebar_selected': "tu-perfil-editar-perfil","usuario":usuario})

@login_required(login_url='publico:login')
def verPerfil(request):
    user = User.objects.get(username=request.user.username)
    usuario = Usuario.objects.get(user_id=user.id)
    avatar = usuario.avatar
    sucursal_usuario = Sucursal.objects.get(id=usuario.sucursal.id)
    return render(request, 'publico/usuario/verPerfil.html',{"usuario":usuario, "avatar":avatar, "sucursal":sucursal_usuario, 'sidebar_selected':"tu-perfil-mis-datos"})

@login_required(login_url='publico:login')
def cambiarContraseniaSuccess(request):
    return render(request, 'publico/usuario/cambiarContraseniaSuccess.html')

@api_view(["GET","POST"])
@login_required(login_url='publico:login')
def cambiarContrasenia(request):
    if (request.method == 'POST'):
        info = request.POST
        user = User.objects.get(username=request.user.username)
        if check_password(info["current_password"],user.password):
            if check_password(info["new_password"],user.password):
                messages.error(request, "Error: La contraseña nueva es igual a la anterior. Intentalo de nuevo.", extra_tags="text-red-400")
                return redirect('publico:cambiarContrasenia')
            else:
                if (info["new_password"]==info["repeat_password"]):
                    user.set_password(info["new_password"])
                    user.save()
                    login(request,user)
                    return redirect('publico:cambiarContraseniaSuccess')
                else:
                    messages.error(request, "Error: Las contraseñas no coinciden. Intentalo de nuevo.", extra_tags="text-red-400")
                    return redirect('publico:cambiarContrasenia')
        else:
            messages.error(request, "Error: La contraseña actual es incorrecta. Intentalo de nuevo.", extra_tags="text-red-400")
            return redirect('publico:cambiarContrasenia')
    else:
        return render(request, 'publico/usuario/cambiarContrasenia.html')

def verUsuario(request, username):
    user_buscado = User.objects.get(username=username)
    usuario_buscado = Usuario.objects.get(user_id=user_buscado.id)
    avatar = usuario_buscado.avatar
    sucursal_usuario = Sucursal.objects.get(id=usuario_buscado.sucursal.id)

    productos_user = list( Producto.objects.filter(usuario_id=username) )

fedeteria/templates/publico/usuario/calificarEmpleado.html
{% extends 'basic-structure-w-sidebar.html' %}{% block title %}
<title>Calificar Empleado | Perfil | Fedeteria</title>
{% endblock %}
{% block second_navbar %}
<a
  href="/perfil"
  class="font-semibold text-gray-400 hover:underline"
>
  Perfil
</a>

<span class="mx-5 font-bold text-gray-500"> / </span>

<a
  href="/perfil/intercambiosTerminados"
  class="font-semibold text-gray-400 hover:underline"
>
  Trueques realizados
</a>
<span class="mx-5 font-bold text-gray-500"> / </span>

<a
  href="/perfil/calificarUsuario"
  class="font-semibold text-gray-400 hover:underline"
>
  Calificar empleado
</a>
{% endblock %}
{% block main %}

<div class="border rounded-md bg-gray-100 shadow-md mx-auto flex w-9/12 flex-col items-center justify-around px-2 py-8">
    <h1 class="text-2xl font-semibold mb-4">Calificar Usuario</h1>
    <form
        class="w-1/2 md:w-full flex flex-col items-center"
        method="post"
    >
        {% csrf_token %}
        <!-- Usuario -->
        <div class="md:w-1/2 bg-gray-300 rounded-lg p-6 mb-6 text-center">
            <div class="flex md:w-5/6 items-center rounded-lg border border-neutral-200 bg-white p-3">
                <img
                    src="/static{{usuario.avatar}}"
                    class="w-10 h-10 md:w-10 md:h-10 object-cover object-center ring-2 ring-orange-300 rounded-full"
                />
                <p class="ms-3 select-none text-neutral-800">
                    <span class="block text-sm font-semibold">
                        {{usuario.user.first_name}} {{usuario.user.last_name}}
                    </span>
                </p>
            </div>
            
            <!-- Estrellas Usuario -->
            <div class="flex justify-left my-4">
                <input type="hidden" name="calificacion_usuario1" id="calificacion-usuario1-input">
                <span class="star-usuario1 cursor-pointer text-gray-400 text-4xl hover:text-yellow-400" data-value="1">&#9733;</span>
                <span class="star-usuario1 cursor-pointer text-gray-400 text-4xl hover:text-yellow-400" data-value="2">&#9733;</span>
                <span class="star-usuario1 cursor-pointer text-gray-400 text-4xl hover:text-yellow-400" data-value="3">&#9733;</span>
                <span class="star-usuario1 cursor-pointer text-gray-400 text-4xl hover:text-yellow-400" data-value="4">&#9733;</span>
                <span class="star-usuario1 cursor-pointer text-gray-400 text-4xl hover:text-yellow-400" data-value="5">&#9733;</span>
            </div>
        </div>
        <button
            type="submit"
            class="group/link flex w-48 items-center justify-center gap-2 px-4 py-2 text-base font-medium text-orange-600 transition-all duration-300 transform bg-orange-200 rounded hover:bg-orange-400 hover:text-orange-900 focus:bg-orange-400 focus:outline-none"
        >
            Enviar Calificacion
        </button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const starsUsuario1 = document.querySelectorAll('.star-usuario1');
        const calificacionUsuario1Input = document.getElementById('calificacion-usuario1-input');

        starsUsuario1.forEach(star => {
            star.addEventListener('click', () => {
                starsUsuario1.forEach(s => s.classList.remove('text-yellow-400', 'selected'));
                star.classList.add('text-yellow-400', 'selected');
                let prevSibling = star.previousElementSibling;
                while (prevSibling) {
                    prevSibling.classList.add('text-yellow-400', 'selected');
                    prevSibling = prevSibling.previousElementSibling;
                }
                const ratingValue = star.getAttribute('data-value');
                calificacionUsuario1Input.value = ratingValue;
                console.log(`Calificación seleccionada para Usuario 1: ${ratingValue}`);
            });
        });

    });
</script>
{% endblock %} 

fedeteria/templates/publico/usuario/listarSolicitudesAceptadas.html
{% extends 'basic-structure-w-sidebar.html' %}{% block title %}
<title>Mis productos | Perfil | Fedeteria</title>
{% endblock %} {% block second_navbar %}
<a
  href="/perfil"
  class="font-semibold text-gray-400 hover:underline"
>
  Perfil
</a>

<span class="mx-5 font-bold text-gray-500"> / </span>

<a
  href="/perfil/solicitudesAceptadas"
  class="font-semibold text-gray-400 hover:underline"
>
  Trueques en proceso
</a>
{% endblock %} {% block main %}
<script>
  async function getImagenProducto(id){
    try {
      const url = 'http://127.0.0.1:8000/api/v1/imgprincipal/' + id;
      const response = await fetch(url);
      if(!response.ok){
        throw new Error("Error en la solicitud");
      }
      //response.text().then((value) => {console.log(value);});
      return response.json();
    } catch (error) {
      console.log(error)
    }
  }
</script>

<!-- Mensajes -->

{% if messages %} 
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div
            class="bg-red-500 text-white p-4 rounded-lg shadow-md"
            role="alert"
        >
            {{ message }}
        </div>
        {% else %}
        <div
            class="bg-green-500 text-white p-4 rounded-lg shadow-md"
            role="alert"
        >
            {{ message }}
        </div>        
        {% endif %}
    {% endfor %} 
{% endif %}





<!--  -->





<div
    class="max-w-[95vw] sm:max-w-5xl w-full border py-8 px-2 sm:px-16 rounded-lg bg-gray-100 shadow-md"
>
      <!-- Solicitudes iniciadas por otros -->

      <h1 class="font-semibold tracking-wide underline text-2xl mb-4">
        Trueques En Proceso
      </h1>
       {% if trueques %}
        <ul
          role="list"
          class=""
        >
          {% for trueque in trueques %}
          {% if trueque.estado == 'Aceptado' or trueque.estado == 'En_Proceso' %}
          <li
            class="relative group flex justify-between gap-x-6 py-5 px-2 flex-wrap transition-all duration-200 ease-in mb-4 hover:rounded-md hover:bg-neutral-200/70"
          >
            <div
              class="flex flex-wrap sm:flex-nowrap justify-between basis-full w-full"
            >
              <!-- <div class="flex min-w-0 gap-x-8"> -->
              <div class="grid grid-cols-3 gap-x-8">
                <div class="min-w-0 flex-initial">
                  <img
                    class="h-32 w-32 flex-none rounded-md bg-neutral-50 object-cover imagen-trueque"
                    src="{{ trueque.producto_1.id }}"
                    alt="{{ trueque.producto_1.id }}"
                  />                  
                  <p
                    class="h-6 overflow-hidden text-sm truncate font-semibold leading-6 text-neutral-900"
                  >
                    {{trueque.producto_1.nombre}}
                  </p>
                </div>


                <div class="min-w-0 flex-auto">
                  <img 
                    class="h-32 w-32 flex-none rounded-md  object-cover"
                    src="/static/public/icons/intercambio.svg">                    
                  </img>
                </div>


                <div class="min-w-0 flex-initial">
                  <img
                    class="h-32 w-32 flex-none rounded-md bg-neutral-50 object-cover imagen-trueque"
                    src="{{ trueque.producto_2.id }}"
                    alt="{{ trueque.producto_2.id }}"
                  />
                  <p
                    class="h-6 overflow-hidden text-sm truncate font-semibold leading-6 text-neutral-900"
                  >
                    {{trueque.producto_2.nombre}}
                  </p>
                </div>                
              </div>
              <div
                class="shrink-0 content-end flex flex-row-reverse w-full justify-between sm:w-fit sm:justify-start sm:flex-col sm:items-end pl-4"
              >

                <div class="mt-1 flex items-center gap-x-1.5">              
                  <p class="text-s leading-5 text-neutral-500">
                    {{trueque.estado}}
                  </p>
                </div>

                <p class="mt-1 text-xs leading-5 text-neutral-500">
                  Fecha inicio: {{ trueque.fecha_inicio }}
                </p>
              </div>
            </div>
            <details
              class="group/details basis-full w-full mt-2 flex transition-all duration-200 ease-in"
            >
              <summary
                class="mb-2 w-full flex justify-between items-center gap-1 cursor-pointer select-none"
              >
                <div class="w-full rounded-md h-[1px] bg-neutral-500/50"></div>
                <p
                  class="flex gap-2 items-center min-w-min text-xs px-1 whitespace-nowrap"
                >
                  Ver opciones
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="1"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="w-4 h-4 group-open/details:rotate-180 group-hover/details:translate-y-0.5 transition-all ease-in"
                  >
                    <path
                      stroke="none"
                      d="M0 0h24v24H0z"
                      fill="none"
                    />
                    <path d="M6 9l6 6l6 -6" />
                  </svg>
                </p>
                <div class="w-full rounded-md h-[1px] bg-neutral-500/50"></div>
              </summary>
              <div
                class="w-full opacity-25 h-0 group-open/details:opacity-100 group-open/details:h-fit flex flex-wrap sm:flex-nowrap justify-evenly items-center space-y-2 sm:space-y-0 gap-2 py-1 transition-all delay-300 duration-200 ease-in"
              >
                <a
                  href="/perfil/verTrueque/{{trueque.id}}"
                  class="basis-2/5 sm:basis-auto flex items-center gap-2 hover:-translate-y-0.5 w-fit px-3 py-1 text-sm font-medium rounded-md bg-neutral-300 transition-all"
                >
                  Ver intercambio
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="w-5 h-5"
                  >
                    <path
                      stroke="none"
                      d="M0 0h24v24H0z"
                      fill="none"
                    />
                    <path d="M17 7l-10 10" />
                    <path d="M8 7l9 0l0 9" />
                  </svg>
                </a>
                <a
                  href="{% url 'trueques:cancelar_trueque' trueque.id %}"
                  class="basis-2/5 sm:basis-auto flex items-center gap-2 hover:-translate-y-0.5 w-fit px-3 py-1 text-sm font-medium rounded-md bg-red-300 transition-all"
                >
                  Cancelar
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="w-5 h-5"
                  >
                    <path
                      stroke="none"
                      d="M0 0h24v24H0z"
                      fill="none"
                    />
                    <path d="M4 7l16 0" />
                    <path d="M10 11l0 6" />
                    <path d="M14 11l0 6" />
                    <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                    <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                  </svg>
                </a>
              </div>
            </details>
          </li>
          {% endif %}          
          {% endfor %}
          <script>
            let imagenes_t = document.getElementsByClassName('imagen-trueque');
            for (let img of imagenes_t){
              let id = img.alt;              
              getImagenProducto(id).then((value) => {img.src=value.image;
              console.log(value.image)});              
            }
          </script>
        </ul>
        {% else %}
        <div class="min-h-64 py-8 px-8 w-full flex flex-col items-center gap-4">
          <p>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.8"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="h-24 w-24 text-neutral-500"
            >
              <path
                stroke="none"
                d="M0 0h24v24H0z"
                fill="none"
              />
              <path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" />
              <path d="M9 13h.01" />
              <path d="M15 13h.01" />
              <path d="M11 17h2" />
            </svg>
          </p>
          <h3 class="text-lg font-medium text-neutral-500">
            No hay ningun trueque en curso
          </h3>
        </div>
        {% endif %}
    </div>
{% endblock main %}