api/urls.py
from django.urls import path
from .views import *

urlpatterns = [    
    path('v1/imgprincipal/<int:pk>', Image_APIView.as_view(), name='imgprincipal'),
    path('v1/imagenes/<int:pk>', Images_APIView.as_view(), name='imagenes'),
    path('v1/producto/<int:pk>', Producto_APIView.as_view(), name='producto'),
    path('v1/productosusuario/<int:pk>', ProductosUsuario_APIView.as_view(), name='productosusuario'),
    path('v1/productos', Productos_APIView.as_view(), name='productos'),
    path('v1/sucursales', Sucursal_APIView.as_view(), name='sucursales'),
    path('v1/categoriasprecio', CategoriaPrecio_APIView.as_view(), name='categoriasprecio'),
    path('v1/estado_producto', EstadoProducto_APIView.as_view(), name='estado_producto'),
    path('v1/estado_producto/<int:id>', EstadoProductoId_APIView.as_view(), name='estado_producto_id'),
    path('v1/promociones/', Promocion_APIView.as_view(), name='promociones'),
    path('v1/es_promocionado/<int:pk>', Promocion_Producto_APIView.as_view(), name='es_promocionado'),
    ]

fedeteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

def notFound(request):
    return render(request, '404.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('publico.urls', 'publico'), namespace='publico')),
    path('administracion/', include(('administracion.urls', 'administracion'), namespace='administracion')),
    path('moderacion/', include(('moderacion.urls', 'moderacion'), namespace='moderacion')),
    path('trueques/', include(('trueques.urls', 'trueques'), namespace='trueques')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('promociones/', include(('promociones.urls', 'promociones'), namespace='promociones')),
    path('404/', notFound),
]

promociones/urls.py
from django.urls import path
from promociones.views import *

urlpatterns = [    
    path('promocionar_producto/<int:idProducto>', promocionar_producto, name='promocionar_producto'),
    #path('pagar/', pagar_promocion, name='pagar'),
    path('detalles/<int:idPromocion>/', ver_detalles_promocion, name='detallePromocion'),
    path('checkout/', payment_view, name='checkout'),
    path('success/', success_view, name='success'),
    path('failure/', failure_view, name='failure'),
    path('pending/', pending_view, name='pending'),
    ]

publico/urls.py
from django.contrib import admin
from django.urls import path, include
from publico.views import *

urlpatterns = [
    # _-_-_-_ _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
    # _-_-_-_ urls sin login required _-_-_-_
    path('', inicio, name='inicio'),
    path('sucursales', sucursales, name='sucursales'),
    path('not-found', notFound, name='not-found'),
    path('emails/register', emailsRegister),

        # productos visualizacion y acciones
    path('productos', verProductos, name='productos'),
    path('productos/producto/<id>', verProducto),

    path('usuario/<username>', verUsuario, name='verUsuario'),   #dni basicamente

        # relacionado a auth
    path('register', registrarUsuario, name='registrarUsuario'),
    path('register/done', registrarSuccess, name='registrarSuccess'),
    path('login', userLogin, name='login'),
    path('logout', logout_view, name='logout'),

    # _-_-_-_ _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
    # _-_-_-_ urls con login required _-_-_-_
    path('perfil', verPerfil, name='perfil'),
    path('perfil/editar', editarPerfil, name='editarPerfil'),

    path('perfil/cambiarcontrasenia', cambiarContrasenia, name='cambiarContrasenia'),
    path('perfil/cambiarcontrasenia/done', cambiarContraseniaSuccess, name='cambiarContraseniaSuccess'),

    # a partir de aca accedido solo por clientes!
    path('perfil/cargarProducto', cargarProducto, name='cargarProducto'),
    path('perfil/cargarProducto/done', cargarProductoSuccess, name='cargarProductoSuccess'),

    path('perfil/productos', verProductosPerfil, name='verProductosPerfil'),
    path('perfil/productos/producto/<id>', verProductoPerfil),
    path('perfil/productos/producto/eliminar/<id>', eliminarProducto, name='eliminarProducto'),
    path('perfil/solicitudes', listarSolicitudesTrueque, name='solicitudesTrueques'),
    path('perfil/solicitudesAceptadas', listarSolicitudesTruequesAceptados, name='intercambiosEnProceso'),
    path('perfil/intercambiosTerminados', listarTruequesTerminados, name='intercambiosTerminados'),
    path('perfil/solicitudesCanceladas', listarSolicitudesCanceladas, name='intercambiosCancelados'),
    path('perfil/verTrueque/<id>', verTrueque, name='verTrueque'),
    path('perfil/calificarUsuario/<id>', calificarUsuario, name='calificarUsuario'),
    path('perfil/calificarUsuarioDone', calificarUsuarioSuccess, name='calificarUsuarioSuccess'),
    ]

promociones/models.py
from django.db import models
from publico.models import Producto

class Promocion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    estado_pago = models.CharField(max_length=50, default='Pendiente')
    duracion = models.IntegerField(null=True)
    fecha_inicio = models.DateField(null=True)
    fecha_fin = models.DateField(null=True)

    def __str__(self):
        return self.nombre

promociones/views.py
from datetime import date, timedelta
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view

from promociones.models import Promocion
from publico.models import Producto

from django.conf import settings
from fedeteria.utilities import create_preference, getPrecioPromocion


@login_required(login_url='publico:login')
def promocionar_producto(request, idProducto):
    '''recibo el id del producto a promocionar en idProducto, creo una nueva promocion y la asocio al producto con idProducto, luego redirijo a la pagina de promociones'''
    producto = Producto.objects.get(id=idProducto)
    if request.method == 'POST':
        promocion = Promocion(producto=producto, duracion=(int(request.POST['duracion'])))
        # Esto se va a hacer posteriormente en el pago con mercado pago
        promocion.estado_pago = 'Pendiente'
        promocion.fecha_inicio = date.today()
        promocion.fecha_fin = promocion.fecha_inicio + timedelta(days=promocion.duracion)
        # Fin de lo que se va a hacer en el pago con mercado pago
        promocion.save()
        item_title = "Promocion de producto: " + producto.nombre + " \npor: " + str(promocion.duracion) + " dias"
        item_quantity = 1
        item_currency_id = "ARS"
        item_unit_price = getPrecioPromocion(int(request.POST['duracion']))

        preference = create_preference(promocion.id, item_title, item_quantity, item_currency_id, item_unit_price, promocion.id)
        print(preference['init_point'])
        return redirect(preference['init_point'])
        # return render(request, 'pago/payment.html', {
        #     'preference_id': preference['id'],
        #     'public_key': settings.MERCADOPAGO_PUBLIC_KEY,
        # })
    return render(request, 'promociones/promocionar_producto.html', {'producto': producto})

@login_required(login_url='publico:login')
def pagar_promocion(request, idPromocion):
    '''redirijo a la pagina de pago de mercado pago'''
    if request.method == 'POST':
        # Aqui se deberia realizar la integracion con mercado pago
        # Una vez que se haya realizado el pago, se deberia cambiar el estado de la promocion a 'Pagado' y asignarle las fechas de inicio y fin
        promocion = Promocion.objects.get(id=idPromocion)
        promocion.estado_pago = 'Pagado'
        promocion.fecha_inicio = date.today()
        promocion.fecha_fin = promocion.fecha_inicio + date.timedelta(days=promocion.duracion)
        promocion.save()
        return redirect('promociones:ver_detalles_promocion', idPromocion=idPromocion)
    return redirect("/not-found")

@login_required(login_url='publico:login')
def ver_detalles_promocion(request, idPromocion):
    '''recibo el id de la promocion a ver en idPromocion y muestro los detalles de la promocion'''
    promocion = Promocion.objects.get(id=idPromocion)
    producto = Producto.objects.get(id=promocion.producto.id)
    return render(request, 'promociones/detalles_promocion.html', {'promocion': promocion, 'producto': producto})


# Integración con Mercado Pago

def payment_view(request):
    if request.method == "POST":
        # Datos de prueba para el ejemplo
        item_title = "Producto de prueba"
        item_quantity = 1
        item_currency_id = "ARS"
        item_unit_price = 100.0

        preference = create_preference(item_title, item_quantity, item_currency_id, item_unit_price)

        return render(request, 'pago/payment.html', {
            'preference_id': preference['id'],
            'public_key': settings.MERCADOPAGO_PUBLIC_KEY,
        })
    return render(request, 'pago/checkout.html')

def success_view(request):
    status = request.GET.get('status')
    external_reference = request.GET.get('external_reference')
    print(status)
    print(external_reference)
    promocion = Promocion.objects.get(id=external_reference)
    promocion.estado_pago = 'Pagado'
    promocion.save()
    return render(request, 'pago/success.html')

def failure_view(request):
    payment_id = request.GET.get('payment_id')
    status = request.GET.get('status')
    merchant_order_id = request.GET.get('merchant_order_id')
    print(payment_id)
    print(status)
    print(merchant_order_id)
    return render(request, 'pago/failure.html')

def pending_view(request):
    payment_id = request.GET.get('payment_id')
    status = request.GET.get('status')
    merchant_order_id = request.GET.get('merchant_order_id')
    print(payment_id)
    print(status)
    print(merchant_order_id)
    return render(request, 'pago/pending.html')

fedeteria/templates/promociones/detalles_promocion.html
{% extends 'basic-structure-w-sidebar.html' %} {% block title %}
<title>Ver Promocion | Fedeteria</title>
{% endblock %} {% block second_navbar %}
<a
  href="/perfil"
  class="font-semibold text-gray-400 hover:underline"
>
  Perfil&nbsp;
</a>
<p   class="font-semibold text-gray-400">
  &nbsp;/&nbsp;
</p>
<a
  href="{% url 'publico:verProductosPerfil' %}"
  class="font-semibold text-gray-400 hover:underline"
>
  &nbsp;Mis Productos
</a>
<p   class="font-semibold text-gray-400">
  &nbsp;/&nbsp;
</p>
<a
  href=""
  class="font-semibold text-gray-400 hover:underline"
>
  &nbsp;Promocion
</a>
{% endblock %} 
{% block main %} {% load static %}
<script>
  async function getImage(id){
    try {
      const url = 'http://127.0.0.1:8000/api/v1/imgprincipal/' + id;
      const response = await fetch(url);
      if(!response.ok){
        throw new Error("Error en la solicitud" + id);
      }
      return response.json();
    } catch (error) {
      console.log(error)
    }
  }
</script>
<div class="flex items-center">    
      <div class="border rounded-md p-8 bg-gray-100 shadow-md mr-8 md:px-32 md:py-8"> 
        <div class="grid grid-cols-2 gap-4 divide-x-8">
            <div
                id="img-container"
                class="w-full hidden h-auto grid-cols-2 aspect-[16/10] overflow-hidden rounded-lg sm:block"            
            >
                <img
                  id="imagen-principal"
                  name="imagen-principal"
                  src=""
                  alt=""
                  class="h-full w-full object-cover object-center"   
                  style="visibility: hidden;"           
                />
            </div>
            <div class="grid grid-rows-8 gap-1 p-8">
              <div class="grid grid-cols-2 gap-2">
                <label for="producto" class="font-semibold text-gray-800">Producto</label>
                <p class="font-semibold text-gray-400">{{ promocion.producto }}</p>
              </div>

              <div class="grid grid-cols-2 gap-2">
                <label for="fecha-inicio" class="font-semibold text-gray-800">Fecha de Inicio</label>
                <p class="font-semibold text-gray-400">{{ promocion.fecha_inicio }}</p>
              </div>              
              <div class="grid grid-cols-2 gap-2">
                <p class="font-semibold text-gray-400 col-start-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="w-5 h-5"
                  >
                    <!-- Flecha hacia arriba -->
                    <path d="M12 22V2m-5 7l5-7 5 7" />
                    <!-- Flecha hacia abajo -->
                    <path d="M12 2v20m5-7l-5 7-5-7" />
                  </svg>
                </p>          
              </div>
              <div class="grid grid-cols-2 gap-2">
                <label for="fecha-fin" class="font-semibold text-gray-800">Fecha de Fin</label>
                <p class="font-semibold text-gray-400">{{ promocion.fecha_fin }}</p>    
              </div>
            </div> 
        </div>              
      </div>    
</div>
<script>
  const idProducto = "{{ promocion.producto.id }}";
  const img = getImage(idProducto);
  img.then(data => {
    const img = document.getElementById('imagen-principal');
    const imgContainer = document.getElementById('img-container');
    img.src = data.image;
    img.style.visibility = 'visible';
    imgContainer.style.visibility = 'visible';
  });
</script>
{% endblock %}

fedeteria/templates/promociones/promocionar_producto.html
{% extends 'basic-structure-w-sidebar.html' %}
{% load static %}
{% block title %}
<title>Ver Perfil | Fedeteria</title>
{% endblock %} 
{% block second_navbar %}
<a
  href="/perfil"
  class="font-semibold text-gray-400 hover:underline"
>
  Perfil
</a>

{% endblock %} 
{% block main %}
<script>
    async function getImagenProducto(id){
      try {
        const url = 'http://127.0.0.1:8000/api/v1/imgprincipal/' + id;
        const response = await fetch(url);
        if(!response.ok){
          throw new Error("Error en la solicitud" + id);
        }
        //response.text().then((value) => {console.log(value);});
        return response.json();
      } catch (error) {
        console.log(error)
      }
    }
</script> 
  <!-- <div class="row-start-1 row-span-1">
    <h1 class="text-2xl font-semibold">Promocionar Producto</h1>
    <p class="text-sm text-gray-500">
        Promociona tu producto para que más personas lo vean y puedan comprarlo.
    </p>
  </div> -->


<!--  -->

  <div class="flex items-baseline justify-between border-b border-neutral-400 pt-6 pb-8 mb-8">
    <div class="flex flex-col space-y-4"> 
      <h1 class="text-4xl font-bold tracking-tight text-neutral-900">
        Promocionar Producto
      </h1>
      <p class="text-sm text-gray-500">
        Promociona tu producto para que más personas lo vean y puedan comprarlo.
      </p> 
    </div>    
  </div>  


<!--  -->


<div class="flex items-center">  
  <div class="border rounded-md p-8 bg-gray-100 shadow-md md:px-32 md:py-8">
    <div class="grid grid-cols-2 gap-x-4 divide-x-8">
        <div class="px-8">
            <!-- Detalles del producto e imagen -->
            <p class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">
                {{producto.nombre}}
            </p>
            <div id="img-container" class="max-w-64 hidden h-auto grid-cols-2 aspect-[16/10]  overflow-hidden rounded-lg sm:block">
                <img
                id="imagen-producto"
                name="imagen-producto"
                src=""
                alt={{producto.nombre}}
                class="h-full w-full object-cover object-center rounded-lg"   
                style="visibility: hidden;"           
                />
            </div>
            <script>
                getImagenProducto("{{producto.id}}").then((data) => {
                    document.getElementById("imagen-producto").src = data.image;
                });
                document.getElementById("imagen-producto").style.visibility = "visible";
            </script>
        </div>
        <div class="px-8">
            <h1 class="text-2xl font-semibold">Promocionar Producto</h1>
            <form action="{% url 'promociones:promocionar_producto' producto.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="duracion" class="block text-sm font-medium text-gray-700">Seleccionar Duración: </label>
                    <select name="duracion" id="duracion" class="mt-2 h-9 min-w-12 max-w-48 w-full pl-3.5 pr-[1.875rem] block rounded-md border-0 px-2 py-1.5 text-neutral-900 shadow-sm outline-none ring-1 ring-inset ring-neutral-300 placeholder:text-neutral-400 hover:ring-1 hover:ring-amber-700 focus:ring-2 focus:ring-inset focus:ring-amber-600 sm:text-sm sm:leading-6" required>
                        <option value="7">1 semana -- $1000 </option>
                        <option value="15">2 semanas -- $1800 </option>
                        <option value="30">1 mes -- $3500 </option>
                    </select>
                </div>
                <button 
                  type="submit"                  
                  class="mt-10 flex w-full items-center justify-center rounded-md border border-transparent bg-orange-400 px-8 py-3 text-base font-medium text-white hover:bg-orange-600 transition-colors"
                >

                    Promocionar
              </button>
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}