api/urls.py
from django.urls import path
from .views import *

urlpatterns = [    
    path('v1/imgprincipal/<int:pk>', Image_APIView.as_view(), name='imgprincipal'),
    path('v1/imagenes/<int:pk>', Images_APIView.as_view(), name='imagenes'),
    path('v1/producto/<int:pk>', Producto_APIView.as_view(), name='producto'),
    path('v1/productosusuario/<int:pk>', ProductosUsuario_APIView.as_view(), name='productosusuario'),
    path('v1/productos', Productos_APIView.as_view(), name='productos'),
    path('v1/sucursales', Sucursal_APIView.as_view(), name='sucursales'),
    path('v1/categoriasprecio', CategoriaPrecio_APIView.as_view(), name='categoriasprecio'),
    path('v1/estado_producto', EstadoProducto_APIView.as_view(), name='estado_producto'),
    path('v1/estado_producto/<int:id>', EstadoProductoId_APIView.as_view(), name='estado_producto_id'),
    path('v1/promociones/', Promocion_APIView.as_view(), name='promociones'),
    path('v1/es_promocionado/<int:pk>', Promocion_Producto_APIView.as_view(), name='es_promocionado'),
    ]

fedeteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

def notFound(request):
    return render(request, '404.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('publico.urls', 'publico'), namespace='publico')),
    path('administracion/', include(('administracion.urls', 'administracion'), namespace='administracion')),
    path('moderacion/', include(('moderacion.urls', 'moderacion'), namespace='moderacion')),
    path('trueques/', include(('trueques.urls', 'trueques'), namespace='trueques')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('promociones/', include(('promociones.urls', 'promociones'), namespace='promociones')),
    path('404/', notFound),
]

publico/urls.py
from django.contrib import admin
from django.urls import path, include
from publico.views import *

urlpatterns = [
    # _-_-_-_ _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
    # _-_-_-_ urls sin login required _-_-_-_
    path('', inicio, name='inicio'),
    path('sucursales', sucursales, name='sucursales'),
    path('not-found', notFound, name='not-found'),
    path('emails/register', emailsRegister),

        # productos visualizacion y acciones
    path('productos', verProductos, name='productos'),
    path('productos/producto/<id>', verProducto),

    path('usuario/<username>', verUsuario, name='verUsuario'),   #dni basicamente

        # relacionado a auth
    path('register', registrarUsuario, name='registrarUsuario'),
    path('register/done', registrarSuccess, name='registrarSuccess'),
    path('login', userLogin, name='login'),
    path('logout', logout_view, name='logout'),

    # _-_-_-_ _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
    # _-_-_-_ urls con login required _-_-_-_
    path('perfil', verPerfil, name='perfil'),
    path('perfil/editar', editarPerfil, name='editarPerfil'),

    path('perfil/cambiarcontrasenia', cambiarContrasenia, name='cambiarContrasenia'),
    path('perfil/cambiarcontrasenia/done', cambiarContraseniaSuccess, name='cambiarContraseniaSuccess'),

    # a partir de aca accedido solo por clientes!
    path('perfil/cargarProducto', cargarProducto, name='cargarProducto'),
    path('perfil/cargarProducto/done', cargarProductoSuccess, name='cargarProductoSuccess'),

    path('perfil/productos', verProductosPerfil, name='verProductosPerfil'),
    path('perfil/productos/producto/<id>', verProductoPerfil),
    path('perfil/productos/producto/eliminar/<id>', eliminarProducto, name='eliminarProducto'),
    path('perfil/solicitudes', listarSolicitudesTrueque, name='solicitudesTrueques'),
    path('perfil/solicitudesAceptadas', listarSolicitudesTruequesAceptados, name='intercambiosEnProceso'),
    path('perfil/intercambiosTerminados', listarTruequesTerminados, name='intercambiosTerminados'),
    path('perfil/solicitudesCanceladas', listarSolicitudesCanceladas, name='intercambiosCancelados'),
    path('perfil/verTrueque/<id>', verTrueque, name='verTrueque'),
    path('perfil/calificarUsuario/<id>', calificarUsuario, name='calificarUsuario'),
    path('perfil/calificarUsuarioDone', calificarUsuarioSuccess, name='calificarUsuarioSuccess'),
    ]

trueques/urls.py
from django.urls import path
from trueques.views import *

urlpatterns = [    
    path('iniciar/<int:id>', seleccionarProductoTrueque, name='iniciar'),
    path('iniciar', iniciarTrueque, name='iniciarTrueque'),
    path('establecer-como-realizado', establecerEstadoRealizado, name='establecerEstadoRealizado'),
    path('establecer-como-no-realizado', establecerEstadoNoRealizado, name='establecerEstadoNoRealizado'),
    path('establecerSucursal/<id>', establecerSucursal, name='establecerSucursal'),
    path('establecerSucursalDone', establecerSucursalSuccess, name='establecerSucursalSuccess'),
    path('aceptartrueque/<int:id>', aceptarTrueque, name='aceptar_trueque'),
    path('cancelartrueque/<int:id>', cancelarTrueque, name='cancelar_trueque'),
]

publico/views.py
import datetime
from django.conf import settings

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib import messages
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.hashers import check_password
from rest_framework.decorators import api_view
from django.core.files.base import ContentFile
from django.db.models import Q
from fedeteria.utilities import actualizar_calificacion_usuario, iniciar_estados_productos, iniciar_sucursales, iniciar_tags, inicializar_categorias_precios, tiempo_pasado
from datetime import date

from promociones.models import Promocion
from publico.models import *
from trueques.models import Trueque

def inicio(request):
    iniciar_sucursales()
    iniciar_tags()
    inicializar_categorias_precios()
    iniciar_estados_productos()
    #productos = Producto.objects.all(filter(estado_publicacion="Activo")) #deberia hacer esto
    productos = Producto.objects.all()[:5] #me quedo con los primeros 5 productos
    _productos = [{'producto': producto,
                   'imagen': Image.objects.get(producto=producto,principal=True),
                   'tags': list(producto.tags.all()),
                   'tiempo_publicacion': tiempo_pasado(producto.fecha_publicacion),
                   } for producto in productos]
    #promociones activas de productos
    destacados = Promocion.objects.filter(Q(estado_pago='Pagado') & Q(fecha_inicio__lte=date.today()) & Q(fecha_fin__gte=date.today()))
    _destacados = [{'producto': Producto.objects.get(id=promocion.producto_id), 'imagen': Image.objects.get(producto_id=promocion.producto_id, principal=True)} for promocion in destacados]
    return render(request, 'publico/landingPage.html',{'productos':_productos, 'destacados':_destacados, 'selected': "inicio"})

def sucursales(request):
    sucursales = Sucursal.objects.all()
    return render(request, "publico/sucursales.html", {'sucursales': sucursales, 'selected': "sucursales"})

def notFound(request):
    return render(request, "publico/not-found.html")

def emailsRegister(request):
    return render(request, "emails/register.html", {'receiver_name': "Juan Manuel Vila"})


''' --------------- Login / Logout ------------------ '''

def logout_view(request):
    logout(request)
    return redirect('publico:inicio')

@api_view(["GET","POST"])
def userLogin(request):
    if request.user.is_authenticated:
        return redirect("/perfil")

    if request.method == 'POST':
        user = authenticate(request, username=request.POST["dni"], password=request.POST["password"])
        if user is not None:
            login(request, user)

            #acá un condicional para redirigir depende del privilegio que tenga el usuario
            if user.has_perm('publico.admin'):
                return redirect('administracion:inicio') #cambiar a pagina admin
            else:
                if user.has_perm('publico.empleado'):
                    return redirect('/moderacion') #cambiar a pagina empleado
                else:
                    return redirect('publico:perfil')
        else:
            messages.error(request, "Usuario o contraseña invalidos...")
            return redirect('publico:login') #redirect!
    else:
        return render(request, 'publico/login/login.html')

''' --------------- Usuarios ------------------ '''

@api_view(["GET","POST"])
def registrarUsuario(request):
    iniciar_sucursales()
    if request.user.is_authenticated:
        return redirect("/perfil")

    if request.method == 'POST':
        info = request.POST
        if info["repeat_password"] != info["password"]:
            messages.error(request, "Error: Las contraseñas no coinciden!", extra_tags="text-red-400")
            return redirect('publico:registrarUsuario')

        try:
            exists = User.objects.get(username=info["dni"], email=info["email"])
            if exists is not None:
                messages.error(request, "Error: Algunos datos ya estan registrados. Intentalo de nuevo o Inicia Sesion", extra_tags="text-yellow-400")
                return redirect('publico:registrarUsuario')
        except:
            #buscando la sucursal segun lo pasado desde el form
            sucursal = Sucursal.objects.get(id=info["sucursal"])

            new_user = User.objects.create_user(
                username= info["dni"],
                first_name = info["first-name"],
                last_name = info["last-name"],
                email = info["email"],
                password = info["password"],
            )
            new_user.save()
            user = User.objects.get(username = info["dni"])
            #Permiso de usuario cliente
            content_type = ContentType.objects.get_for_model(Permisos)
            permiso = Permission.objects.get(codename='cliente', content_type=content_type)
            # Asignar el permiso al usuario
            user.user_permissions.add(permiso)
            usuario = Usuario.objects.create(
                user = user,
                fecha_nacimiento = info["born"],
                avatar = info["avatar"],
                telefono = info["phone"],
                sucursal_id = sucursal.id,
                ofertas = info.get("offers") is not None,
            )
            usuario.save()

            subject = 'Bienvenido '+ user.first_name +'. Ahora a intercambiar!'
            convert_to_html_content =  render_to_string(
                template_name= 'emails/register.html',
                context= {
                    'user': user,
                    'usuario': usuario
                }
            )
            plain_message = strip_tags(convert_to_html_content)
            send_mail(
                subject=subject,
                message=plain_message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email],   # recipient_list is self explainatory
                html_message=convert_to_html_content,
            )

            return redirect("/register/done")
    else:
        return render(request, 'publico/login/registrarUsuario.html')

def registrarSuccess(request):
    if request.user.is_authenticated:
        return redirect("/perfil")
    return render(request, "publico/login/registrarSuccess.html")


@api_view(["GET","POST"])
@login_required(login_url='publico:login')
def editarPerfil(request):
    if request.method == 'POST':
        info = request.POST
        user = User.objects.get(username=request.user.username)
        usuario = Usuario.objects.get(user_id=user.id)
        user.first_name = info["first-name"]
        user.last_name = info["last-name"]
        user.email = info["email"]
        user.save()
        usuario.avatar = info["avatar"]
        usuario.telefono = info["phone"]
        usuario.fecha_nacimiento = info["born"]
        usuario.ofertas = info.get("offers") is not None
        usuario.sucursal = Sucursal.objects.get(id=info["sucursal"])
        usuario.save()
        return render(request, 'publico/usuario/editarPerfilSuccess.html')
    usuario = Usuario.objects.get(user_id=request.user.id)
    return render(request, 'publico/usuario/editarPerfil.html', {'sidebar_selected': "tu-perfil-editar-perfil","usuario":usuario})

@login_required(login_url='publico:login')
def verPerfil(request):
    user = User.objects.get(username=request.user.username)
    usuario = Usuario.objects.get(user_id=user.id)
    avatar = usuario.avatar
    sucursal_usuario = Sucursal.objects.get(id=usuario.sucursal.id)
    return render(request, 'publico/usuario/verPerfil.html',{"usuario":usuario, "avatar":avatar, "sucursal":sucursal_usuario, 'sidebar_selected':"tu-perfil-mis-datos"})

@login_required(login_url='publico:login')
def cambiarContraseniaSuccess(request):
    return render(request, 'publico/usuario/cambiarContraseniaSuccess.html')

@api_view(["GET","POST"])
@login_required(login_url='publico:login')
def cambiarContrasenia(request):
    if (request.method == 'POST'):
        info = request.POST
        user = User.objects.get(username=request.user.username)
        if check_password(info["current_password"],user.password):
            if check_password(info["new_password"],user.password):
                messages.error(request, "Error: La contraseña nueva es igual a la anterior. Intentalo de nuevo.", extra_tags="text-red-400")
                return redirect('publico:cambiarContrasenia')
            else:
                if (info["new_password"]==info["repeat_password"]):
                    user.set_password(info["new_password"])
                    user.save()
                    login(request,user)
                    return redirect('publico:cambiarContraseniaSuccess')
                else:
                    messages.error(request, "Error: Las contraseñas no coinciden. Intentalo de nuevo.", extra_tags="text-red-400")
                    return redirect('publico:cambiarContrasenia')
        else:
            messages.error(request, "Error: La contraseña actual es incorrecta. Intentalo de nuevo.", extra_tags="text-red-400")
            return redirect('publico:cambiarContrasenia')
    else:
        return render(request, 'publico/usuario/cambiarContrasenia.html')

def verUsuario(request, username):
    user_buscado = User.objects.get(username=username)
    usuario_buscado = Usuario.objects.get(user_id=user_buscado.id)
    avatar = usuario_buscado.avatar
    sucursal_usuario = Sucursal.objects.get(id=usuario_buscado.sucursal.id)

    productos_user = list( Producto.objects.filter(usuario_id=username) )

fedeteria/templates/publico/productos/cargarProductoSuccess.html
{% extends 'basic-structure-w-sidebar.html' %}{% block title %}
<title>Cargar producto | Fedeteria</title>
{% endblock %} {% block second_navbar %}
<a
  href="{% url 'publico:perfil' %}"
  class="font-semibold text-gray-400 hover:underline"
>
  Perfil
</a>

<span class="mx-5 font-bold text-gray-500"> / </span>
<a class="font-semibold text-gray-400"> Cargar Producto </a>
{% endblock %} {% block main %}
<div
  class="my-auto flex min-h-full flex-col justify-center max-w-[95vw] sm:max-w-5xl w-full border py-8 px-16 rounded-lg bg-gray-100 shadow-md"
>
  <div
    class="mt-10 max-w-[95vw] sm:mx-auto sm:w-full sm:max-w-5xl h-full px-8 py-12 flex flex-col gap-4 items-center justify-center"
  >
    <style>
      .success-checkmark {
        width: 80px;
        height: 115px;
        margin: 0 auto;

        .check-icon {
          width: 80px;
          height: 80px;
          position: relative;
          border-radius: 50%;
          box-sizing: content-box;
          border: 4px solid #4caf50;

          &::before {
            top: 3px;
            left: -2px;
            width: 30px;
            transform-origin: 100% 50%;
            border-radius: 100px 0 0 100px;
          }

          &::after {
            top: 0;
            left: 30px;
            width: 60px;
            transform-origin: 0 50%;
            border-radius: 0 100px 100px 0;
            animation: rotate-circle 4.25s ease-in;
          }

          &::before,
          &::after {
            content: "";
            height: 100px;
            position: absolute;
            background: #ffffff;
            transform: rotate(-45deg);
          }

          .icon-line {
            height: 5px;
            background-color: #4caf50;
            display: block;
            border-radius: 2px;
            position: absolute;
            z-index: 10;

            &.line-tip {
              top: 46px;
              left: 14px;
              width: 25px;
              transform: rotate(45deg);
              animation: icon-line-tip 1.5s 0.5s;
            }

            &.line-long {
              top: 38px;
              right: 8px;
              width: 47px;
              transform: rotate(-45deg);
              animation: icon-line-long 1.5s 0.5s;
            }
          }

          .icon-circle {
            top: -4px;
            left: -4px;
            z-index: 10;
            width: 80px;
            height: 80px;
            border-radius: 50%;
            position: absolute;
            box-sizing: content-box;
            border: 4px solid rgba(76, 175, 80, 0.5);
          }

          .icon-fix {
            top: 8px;
            width: 5px;
            left: 26px;
            z-index: 1;
            height: 85px;
            position: absolute;
            transform: rotate(-45deg);
            background-color: #ffffff;
          }
        }
      }

      @keyframes rotate-circle {
        0% {
          transform: rotate(-45deg);
        }
        5% {
          transform: rotate(-45deg);
        }
        12% {
          transform: rotate(-405deg);
        }
        100% {
          transform: rotate(-405deg);
        }
      }

      @keyframes icon-line-tip {
        0% {
          width: 0;
          left: 1px;
          top: 19px;
        }
        54% {
          width: 0;
          left: 1px;
          top: 19px;
        }
        70% {
          width: 50px;
          left: -8px;
          top: 37px;
        }
        84% {
          width: 17px;
          left: 21px;
          top: 48px;
        }
        100% {
          width: 25px;
          left: 14px;
          top: 45px;
        }
      }

      @keyframes icon-line-long {
        0% {
          width: 0;
          right: 46px;
          top: 54px;
        }
        65% {
          width: 0;
          right: 46px;
          top: 54px;
        }
        84% {
          width: 55px;
          right: 0px;
          top: 35px;
        }
        100% {
          width: 47px;
          right: 8px;
          top: 38px;
        }
      }
    </style>
    <div class="success-checkmark">
      <div class="check-icon">
        <span class="icon-line line-tip"></span>
        <span class="icon-line line-long"></span>
        <div class="icon-circle"></div>
        <div class="icon-fix"></div>
      </div>
    </div>
    <h1 class="text-2xl font-medium tracking-wider underline">
      Producto cargado con exito!
    </h1>
    <p>
      En las siguientes horas uno de nuestros empleados va a asignarle el precio
      a tu producto.
    </p>
    <p>
      Una vez el precio esté asignado, tu producto estará listo para un
      intercambio!.
    </p>
  </div>
</div>
{% endblock %}

fedeteria/templates/publico/productos/verProducto.html
{% extends 'basic-structure-w-footer.html' %}{% block title %}
<title>{{producto.nombre}} | Productos publicados | Fedeteria</title>
{% endblock %} {% block main %} {% load static %}
<div class="bg-white">
  <div class="relative">
    <a
      href="/productos"
      class="absolute group -mt-16 ml-0 sm:ml-4 w-fit px-4 py-1 text-neutral-400 flex items-center gap-2 hover:underline hover:text-neutral-700"
      ><svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="h-5 w-5 group-hover:-translate-x-1 transition-all"
      >
        <path
          stroke="none"
          d="M0 0h24v24H0z"
          fill="none"
        />
        <path d="M5 12l14 0" />
        <path d="M5 12l4 4" />
        <path d="M5 12l4 -4" />
      </svg>
      Volver
    </a>
    <!-- Product info -->
    <div
      class="mx-auto max-w-2xl px-4 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:px-8"
    >
      <div
        class="w-full h-auto grid-cols-2 aspect-[16/12] overflow-hidden rounded-lg block sm:hidden mb-4"
      >
        <img
          src="{{imagen_principal}}"
          alt="imagen de {{producto.nombre}}"
          class="h-full w-full object-cover object-center"
        />
      </div>
      <!-- Title and price with owner info -->
      <div class="lg:col-start-3 lg:row-span-3 lg:col-span-1 lg:mt-0">
        <div class="flex items-center gap-x-1.5">
          {% if producto.estado_publicacion == "Activo" %}
          <div class="flex-none rounded-full bg-green-500/20 p-1">
            <div class="h-1.5 w-1.5 rounded-full bg-green-500"></div>
          </div>
          <p class="text-xs leading-5 text-neutral-500">
            {{producto.estado_publicacion}}
          </p>
          {% else %}
          <div class="flex-none rounded-full bg-blue-500/20 p-1">
            <div class="h-1.5 w-1.5 rounded-full bg-blue-500"></div>
          </div>
          <p class="text-xs leading-5 text-neutral-500">
            {{producto.estado_publicacion}}
          </p>
          {% endif %}
        </div>
        <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">
          {{producto.nombre}}
        </h1>

        <h2 class="sr-only">Product price</h2>
        <p class="text-3xl tracking-tight text-gray-900">
          {% if producto.cat_precio is None %}
          <!--  -->
          ---
          <!--  -->
          {% else %}
          <!--  -->
          Clase {{producto.cat_precio.nombre}}
          <!--  -->
          {% endif %}
        </p>
        <p class="text-base font-medium text-gray-500">
          {{producto.estado_producto.nombre}}
        </p>
        <!-- <p class="text-xs font-ligth text-gray-500">
          Publicado {{ tiempo_publicacion }}
        </p> -->

        <div class="">
          {% if request.user.username != duenio.username and producto.estado_publicacion != "Pausado" %}
          <a
            href="{% url 'trueques:iniciar' producto.id %}"
            class="mt-10 flex w-full items-center justify-center rounded-md border border-transparent bg-orange-400 px-8 py-3 text-base font-medium text-white hover:bg-orange-600 transition-colors"
          >
            Iniciar oferta
          </a>
          {% else %}
          <p
            class="mt-10 flex w-full items-center justify-center rounded-md border border-transparent bg-orange-400 opacity-50 px-8 py-3 text-base font-medium text-white transition-colors"
          >
            Iniciar oferta
          </p>
          {% endif %}
        </div>

        <!-- Owner info and Reviews -->
        <div class="mt-8 border-t py-4">
          <div class="flex flex-col gap-2 py-4 rounded-lg">
            <div class="flex items-center">
              <img
                class="object-cover mx-2 rounded-md w-14 shrink-0 h-14 ring-4 ring-gray-300"
                src="/static{{duenio.avatar}}"
                alt="avatar usuario"
              />

              <div class="flex flex-col mx-2">
                <h1 class="font-semibold text-gray-800">
                  {{duenio.nombre}} {{duenio.apellido}}
                </h1>
                <span class="text-sm text-gray-500">{{duenio.email}}</span>
                <span class="text-sm text-gray-500">{{duenio.telefono}}</span>
              </div>
            </div>
            <div class="flex w-full items-center py-1 px-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="mt-0.5 shrink-0 h-5 w-5"
              >
                <path
                  stroke="none"
                  d="M0 0h24v24H0z"
                  fill="none"
                />
                <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" />
                <path d="M6 21v-2a4 4 0 0 1 4 -4h.5" />
                <path
                  d="M17.8 20.817l-2.172 1.138a.392 .392 0 0 1 -.568 -.41l.415 -2.411l-1.757 -1.707a.389 .389 0 0 1 .217 -.665l2.428 -.352l1.086 -2.193a.392 .392 0 0 1 .702 0l1.086 2.193l2.428 .352a.39 .39 0 0 1 .217 .665l-1.757 1.707l.414 2.41a.39 .39 0 0 1 -.567 .411l-2.172 -1.138z"
                />
              </svg>
              <p class="ms-3 text-neutral-800">
                <span class="block text-sm opacity-70"> Valoracion: </span>
                <span class="flex items-center text-sm font-semibold">
                  {% if duenio.calificacion is None or duenio.num_calificaciones == 0 %}
                    Sin calificacion
                  {% else %}
                  <span class="opacity-100 text-sm">{{duenio.calificacion}} </span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="mt-0.5 shrink-0 h-4 w-4 fill-orange-200 stroke-orange-400"
                  >
                    <path
                      stroke="none"
                      d="M0 0h24v24H0z"
                      fill="none"
                    />
                    <path
                      d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z"
                    />
                  </svg> 
                  
                  <span class="opacity-60 text-xs ml-2">
                    - {{duenio.num_calificaciones}} calificaciones
                  </span>
                  {% endif %}
                  

                </span>
              </p>
            </div>
            <div class="flex w-full items-center py-1 px-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="mt-0.5 shrink-0 h-5 w-5"
              >
                <path
                  stroke="none"
                  d="M0 0h24v24H0z"
                  fill="none"
                />
                <path d="M12 18.5l-3 -1.5l-6 3v-13l6 -3l6 3l6 -3v7.5" />
                <path d="M9 4v13" />
                <path d="M15 7v5.5" />
                <path
                  d="M21.121 20.121a3 3 0 1 0 -4.242 0c.418 .419 1.125 1.045 2.121 1.879c1.051 -.89 1.759 -1.516 2.121 -1.879z"
                />
                <path d="M19 18v.01" />
              </svg>
              <p class="ms-3 text-neutral-800">
                <span class="block text-sm opacity-70">
                  Sucursal preferida:
                </span>
                <span class="block text-sm font-semibold">
                  {{duenio.sucursal.localidad}} -
                  <span class="opacity-60 text-xs"
                    >{{duenio.sucursal.direccion}}</span
                  >
                </span>
              </p>
            </div>
            <a
              href="/usuario/{{duenio.username}}"
              class="flex w-full items-center justify-center rounded-md border border-transparent bg-orange-200 px-2 py-1 text-base font-medium text-orange-400 hover:bg-orange-300 hover:text-orange-7 00 transition-colors"
            >
              Ver informacion del vendedor
            </a>
          </div>
        </div>
      </div>

      <div
        class="py-10 lg:col-span-2 lg:col-start-1 lg:border-r lg:border-gray-200 lg:pb-16 lg:pr-8 lg:pt-0"
      >
        <!-- primary Image -->
        <div
          class="w-full hidden h-auto grid-cols-2 aspect-[16/10] overflow-hidden rounded-lg sm:block"
        >
          <img
            src="{{imagen_principal}}"
            alt="Two each of gray, white, and black shirts laying flat."
            class="h-full w-full object-cover object-center"
          />
        </div>

        <div class="flex justify-start items-center gap-2 mt-5">
          {% for categoria in categorias %}
          <a
            class="bg-neutral-800 text-neutral-200 rounded-md text-xs h-fit px-2 py-0.5 transition-all ease-out hover:-translate-y-0.5"
            href="/productos?categorias={{ categoria.id }}"
          >
            {{ categoria}}
          </a>
          {% endfor %}
        </div>

        <!-- Description and details -->
        <div class="mt-5">
          <h3 class="">Descripcion:</h3>
          <div class="space-y-6">
            <p class="text-base text-gray-900">{{producto.descripcion}}</p>
          </div>
        </div>
      </div>
      <!-- Imágenes secundarias -->
      {% if imagenes_secundarias %}

      <div class="col-span-full max-w-2xl mt-16 my-8">
        <h3 class="text-lg underline font-medium text-gray-900">
          Galeria de imagenes
        </h3>
      </div>
      <div
        class="col-span-full mx-auto w-full max-w-2xl gap-x-4 gap-y-16 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:grid-rows-[auto,auto,1fr]"
      >
        {% for imagen in imagenes_secundarias %}
        <div
          class="w-full max-h-64 grid-cols-1 aspect-square overflow-hidden rounded-lg mt-8 sm:mt-0"
        >
          <img
            src="{{imagen}}"
            alt="{{imagen.nombre}}"
            class="h-full w-full object-cover object-center"
          />
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>

  {% endblock %}
</div>